    - name: Retrieve job template list for each inventory and store in a dictionary
      ansible.builtin.uri:
        url: "https://{{ automation_controller_host }}/api/v2/job_templates/?inventory_id={{ item.id }}"
        method: GET
        # user: "{{ controller_username }}"
        # password: "{{ controller_password }}"
        # force_basic_auth: true
        validate_certs: "{{ verify_ssl }}"
        return_content: true
        headers:
          Authorization: "Bearer 2QnGTupS1bVWMF4wJ8PePxUUjlOe4i"
      loop: "{{ controller_inventory }}"
      loop_control:
        label: "{{ item.name }}"
      register: job_template_list_results