---
- name: Retrieve inventory from Ansible Automation Controller
  hosts: localhost
  gather_facts: false


  tasks:
    - name: Include secrets
      include_vars: secret.yml

    - name: Load the inventory from Automation Controller using the connection info
      set_fact:
        controller_inventory: "{{ lookup('awx.awx.controller_api', 'inventories?page_size=200',
                                          host=automation_controller_host,
                                          username=controller_username,
                                          password=controller_password,
                                          verify_ssl=verify_ssl) }}"

    # - name: Load the inventory from Automation Controller using the connection info
    #   set_fact:
    #     controller_inventory: "{{ lookup('awx.awx.controller_api', 'inventories',
    #                                       host=automation_controller_host,
    #                                       username=controller_username,
    #                                       password=controller_password,
    #                                       verify_ssl=verify_ssl) }}"

    # - name: Load the inventory from Automation Controller using the connection info
    #   set_fact:
    #     "inventory_{{ item.id }}": "{{ lookup('awx.awx.controller_api', 'inventories/' + item.id|string,
    #                                       host=automation_controller_host,
    #                                       username=controller_username,
    #                                       password=controller_password,
    #                                       verify_ssl=verify_ssl) }}"
    #     job_list_dict: "{{ job_list_dict | default({}) | combine({item.id: lookup('awx.awx.controller_api', 'jobs/?inventory_id=' + item.id|string,
    #                                     host=automation_controller_host,
    #                                     username=controller_username,
    #                                     password=controller_password,
    #                                     verify_ssl=verify_ssl)}) }}"
    #   loop: "{{ controller_inventory }}"
    #   loop_control:
    #     label: "{{ item.name }}"

    # - name: Display retrieved inventory data
    #   debug:
    #     var: controller_inventory

    # - name: Print all host_vars
    #   debug:
    #     var: hostvars.localhost

    - name: Retrieve job template list for each inventory and store in a dictionary
      ansible.builtin.uri:
        url: "https://{{ automation_controller_host }}/api/v2/job_templates/?inventory_id={{ item.id }}"
        method: GET
        user: "{{ controller_username }}"
        password: "{{ controller_password }}"
        force_basic_auth: yes
        validate_certs: "{{ verify_ssl }}"
        return_content: yes
      loop: "{{ controller_inventory }}"
      loop_control:
        label: "{{ item.name }}"
      register: job_template_list_results

    - name: Combine job template list into a dictionary
      set_fact:
        job_template_list_dict: "{{ job_template_list_dict | default({}) | combine({item.id: (job_template_list_results.results | selectattr('item.id', 'eq', item.id) | map(attribute='content') | map('from_json'))[0] }) }}"
      loop: "{{ controller_inventory }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Retrieve job list for each inventory and store in a dictionary
      ansible.builtin.uri:
        url: "https://{{ automation_controller_host }}/api/v2/jobs/?inventory_id={{ item.id }}"
        method: GET
        user: "{{ controller_username }}"
        password: "{{ controller_password }}"
        force_basic_auth: yes
        validate_certs: "{{ verify_ssl }}"
        return_content: yes
      loop: "{{ controller_inventory }}"
      loop_control:
        label: "{{ item.name }}"
      register: job_list_results

    - name: Combine job list into a dictionary
      set_fact:
        job_list_dict: "{{ job_list_dict | default({}) | combine({item.id: (job_list_results.results | selectattr('item.id', 'eq', item.id) | map(attribute='content') | map('from_json'))[0] }) }}"
      loop: "{{ controller_inventory }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Display combined job list dictionary
      ansible.builtin.debug:
        var: job_list_dict


- name: Build report with facts - Dynamic Documentation
  hosts: "{{ _hosts | default('localhost') }}"
  gather_facts: true

  tasks:
    - name: Template report into HTML
      ansible.builtin.include_role:
        name: "template"

    - name: Load report to host on AWS S3
      ansible.builtin.include_role:
        name: "build_report_s3"
      when: inventory_hostname == 'localhost'