---
- name: Retrieve inventory from Ansible Automation Controller
  hosts: localhost
  gather_facts: false


  tasks:
    - name: Include secrets
      include_vars: secret.yml

    - name: Load the inventory from Automation Controller using the connection info
      ansible.builtin.set_fact:
        job_list_dict: "{{ lookup('awx.awx.controller_api', 'jobs/?inventory_id=8',
                                          host=automation_controller_host,
                                          username=controller_username,
                                          password=controller_password,
                                          verify_ssl=verify_ssl) }}"

    - name: debug the output
      ansible.builtin.debug:
        msg: "{{ job_list_dict }}"

    - name: debug the output
      ansible.builtin.debug:
        msg: "length is {{ job_list_dict | length }}"